name: counter_repository
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.2"

dependencies:
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  test: ^1.19.5
  very_good_analysis: ^2.4.0
